### ISSUE TITLE
[PE-D] Specify flag while adding not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-2/tp#167]
![image.png](https://raw.githubusercontent.com/TeddYE/ped/main/files/f4e2857d-ccaa-4a9f-8c3e-e44a646f198b.png)

add n/p1 p/111 e/e@e.com a/a1 f/true
* p1 not flagged as intended

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: TeddYE/ped#1

**Comment by Vishwanth2210** [comment]
Hi! Thank you for bringing this up. Sorry for the misdirection in the `add` command usage, but flag only works through the `flag` and `unflag` commands. We will update the command usage accordingly if it is within the constrain of v1.4.
